### ISSUE TITLE
Kernel panic on iOS 16.6b1 iPhone 14.

### ISSUE THREAD

**Issue by lumen-novum** [leminlimez/Chicken-Butt#2]
I'm currently using Chicken Butt v1.1 beta 1 and whenever I try to apply tweaks, my iPhone 14 crashes.

I've tried both ipas.

I can upload logs if you'd like. (I'm not quite sure where the kernel panic logs would be, but I did get a pop up once about it)

**Comment by Vikram1807** [comment]
Panic log on setting - privacy -analytics search panic full

**Comment by lumen-novum** [comment]
Fixed on Cluckabunga 2.0 beta 1.
